FROM oven/bun:1
# FROM node:20


RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs


WORKDIR /usr/src/backend

COPY package.json bun.lockb .
COPY ./prisma .

RUN bun install
RUN bun prisma generate

COPY . .

EXPOSE 3002

CMD ["bun", "run","dev"]